//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.AdoModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PM : DbContext
    {
        public PM()
            : base("name=PM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<RoleMenu> RoleMenu { get; set; }
        public virtual DbSet<ServerInfo> ServerInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<WorkDefinition> WorkDefinition { get; set; }
    
        public virtual ObjectResult<SP_Action_Result> SP_Action()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Action_Result>("SP_Action");
        }
    
        public virtual ObjectResult<SP_STATISTIC_Result> SP_STATISTIC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_STATISTIC_Result>("SP_STATISTIC");
        }
    }
}
