//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenu
    {
        public string Id { get; set; }
        public string Role_Id { get; set; }
        public string Menu_Id { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
