//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDefinition
    {
        public string Id { get; set; }
        public string User_Id { get; set; }
        public string Project_Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int Rank { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
